/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { type JSX } from 'react'
import * as THREE from 'three'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Krychle002: THREE.Mesh
    Krychle003: THREE.Mesh
    Krychle004: THREE.Mesh
    Krychle005: THREE.Mesh
    Krychle006: THREE.Mesh
    Krychle007: THREE.Mesh
    Table: THREE.Mesh
    Krychle010_1: THREE.Mesh
    Krychle010_2: THREE.Mesh
    Krychle011: THREE.Mesh
    Krychle012: THREE.Mesh
    Krychle013: THREE.Mesh
    Kruh_1: THREE.Mesh
    Kruh_2: THREE.Mesh
    Kruh001_1: THREE.Mesh
    Kruh001_2: THREE.Mesh
    Krychle014: THREE.Mesh
    Krychle015: THREE.Mesh
    Krychle016: THREE.Mesh
    Válec_1: THREE.Mesh
    Válec_2: THREE.Mesh
    Válec001: THREE.Mesh
    Válec002: THREE.Mesh
    Krychle017: THREE.Mesh
    Krychle018: THREE.Mesh
    Krychle019: THREE.Mesh
    Krychle020: THREE.Mesh
    Krychle024_1: THREE.Mesh
    Krychle024_2: THREE.Mesh
    Krychle025_1: THREE.Mesh
    Krychle025_2: THREE.Mesh
    Krychle023: THREE.Mesh
    Krychle024: THREE.Mesh
    Krychle025: THREE.Mesh
    Válec003: THREE.Mesh
    Válec004: THREE.Mesh
    Krychle030_1: THREE.Mesh
    Krychle030_2: THREE.Mesh
    Krychle030_3: THREE.Mesh
    Krychle032: THREE.Mesh
    Krychle032_1: THREE.Mesh
    Krychle072_1: THREE.Mesh
    Krychle072_2: THREE.Mesh
    Mouse: THREE.Mesh
    Válec005: THREE.Mesh
    Krychle030: THREE.Mesh
    Krychle027_1: THREE.Mesh
    Krychle027_2: THREE.Mesh
    Krychle027_3: THREE.Mesh
    Krychle027_4: THREE.Mesh
    Krychle033: THREE.Mesh
    Krychle033_1: THREE.Mesh
    Krychle033_2: THREE.Mesh
    Válec006_1: THREE.Mesh
    Válec006_2: THREE.Mesh
    Válec007: THREE.Mesh
    Válec010: THREE.Mesh
    Válec014: THREE.Mesh
    Válec016: THREE.Mesh
    Plocha001_1: THREE.Mesh
    Plocha001_2: THREE.Mesh
    Válec017: THREE.Mesh
    Plocha002_1: THREE.Mesh
    Plocha002_2: THREE.Mesh
    Bezierova_křivka: THREE.Mesh
    Bezierova_křivka002: THREE.Mesh
    Bezierova_křivka003: THREE.Mesh
    Bezierova_křivka004: THREE.Mesh
    Bezierova_křivka005: THREE.Mesh
    Bezierova_křivka001: THREE.Mesh
    Krychle008: THREE.Mesh
    Krychle009: THREE.Mesh
    Krychle010: THREE.Mesh
    Válec008: THREE.Mesh
    Válec009: THREE.Mesh
    Válec011: THREE.Mesh
    Krychle036_1: THREE.Mesh
    Krychle036_2: THREE.Mesh
    Krychle036_3: THREE.Mesh
    Krychle036_4: THREE.Mesh
    Válec012_1: THREE.Mesh
    Válec012_2: THREE.Mesh
    Krychle026: THREE.Mesh
    Krychle028: THREE.Mesh
    Krychle034: THREE.Mesh
    Krychle034_1: THREE.Mesh
    Krychle035: THREE.Mesh
    Krychle036: THREE.Mesh
    Krychle037: THREE.Mesh
    Krychle055: THREE.Mesh
    Válec013: THREE.Mesh
    Válec015: THREE.Mesh
    Krychle061: THREE.Mesh
    Krychle078: THREE.Mesh
    Krychle078_1: THREE.Mesh
    Válec022_1: THREE.Mesh
    Válec022_2: THREE.Mesh
    Válec023_1: THREE.Mesh
    Válec023_2: THREE.Mesh
    Válec024_1: THREE.Mesh
    Válec024_2: THREE.Mesh
    Válec025_1: THREE.Mesh
    Válec025_2: THREE.Mesh
    Válec026_1: THREE.Mesh
    Válec026_2: THREE.Mesh
    Válec027_1: THREE.Mesh
    Válec027_2: THREE.Mesh
    Válec028_1: THREE.Mesh
    Válec028_2: THREE.Mesh
    Válec029_1: THREE.Mesh
    Válec029_2: THREE.Mesh
    Válec030_1: THREE.Mesh
    Válec030_2: THREE.Mesh
    Krychle046: THREE.Mesh
    Krychle046_1: THREE.Mesh
    Krychle046_2: THREE.Mesh
    Krychle046_3: THREE.Mesh
    Krychle046_4: THREE.Mesh
    Krychle046_5: THREE.Mesh
    Krychle046_6: THREE.Mesh
    Krychle046_7: THREE.Mesh
    Krychle046_8: THREE.Mesh
    Krychle046_9: THREE.Mesh
    Krychle046_10: THREE.Mesh
    Krychle046_11: THREE.Mesh
    Krychle046_12: THREE.Mesh
    Krychle046_13: THREE.Mesh
    Krychle046_14: THREE.Mesh
    Krychle046_15: THREE.Mesh
    Krychle046_16: THREE.Mesh
    Krychle046_17: THREE.Mesh
    Krychle046_18: THREE.Mesh
    Krychle072: THREE.Mesh
    Krychle073: THREE.Mesh
    Válec032: THREE.Mesh
    Válec032_1: THREE.Mesh
    Válec029: THREE.Mesh
    Válec030: THREE.Mesh
  }
  materials: {
    ['Materiál.002']: THREE.MeshStandardMaterial
    ['Materiál.003']: THREE.MeshPhysicalMaterial
    ['Materiál.005']: THREE.MeshStandardMaterial
    ['Materiál.008']: THREE.MeshStandardMaterial
    ['Materiál.006']: THREE.MeshStandardMaterial
    ['Materiál.007']: THREE.MeshStandardMaterial
    ['Materiál.015']: THREE.MeshStandardMaterial
    ['Materiál.009']: THREE.MeshPhysicalMaterial
    ['Materiál.012']: THREE.MeshStandardMaterial
    ['Materiál.011']: THREE.MeshStandardMaterial
    ['Materiál.013']: THREE.MeshStandardMaterial
    ['Materiál.016']: THREE.MeshStandardMaterial
    ['Materiál.014']: THREE.MeshStandardMaterial
    ['Materiál.018']: THREE.MeshStandardMaterial
    ['Materiál.019']: THREE.MeshStandardMaterial
    ['Materiál.020']: THREE.MeshPhysicalMaterial
    ['Materiál.021']: THREE.MeshPhysicalMaterial
    ['Materiál.022']: THREE.MeshPhysicalMaterial
    ['Materiál.023']: THREE.MeshStandardMaterial
    ['Materiál.010']: THREE.MeshPhysicalMaterial
    ['Materiál.017']: THREE.MeshPhysicalMaterial
    ['Materiál.024']: THREE.MeshStandardMaterial
    ['Materiál.025']: THREE.MeshStandardMaterial
    ['Materiál.026']: THREE.MeshStandardMaterial
    ['Materiál.027']: THREE.MeshStandardMaterial
    ['Materiál.038']: THREE.MeshStandardMaterial
    ['Materiál.037']: THREE.MeshPhysicalMaterial
    ['Materiál.032']: THREE.MeshStandardMaterial
    ['Materiál.004']: THREE.MeshStandardMaterial
    ['Materiál.035']: THREE.MeshStandardMaterial
    ['Materiál.036']: THREE.MeshStandardMaterial
    ['Materiál.040']: THREE.MeshPhysicalMaterial
    ['Materiál.041']: THREE.MeshStandardMaterial
    ['Materiál.029']: THREE.MeshStandardMaterial
    ['Materiál.031']: THREE.MeshPhysicalMaterial
    ['Materiál.042']: THREE.MeshPhysicalMaterial
    ['Materiál.044']: THREE.MeshPhysicalMaterial
    ['Materiál.045']: THREE.MeshStandardMaterial
    ['Materiál.054']: THREE.MeshPhysicalMaterial
    ['Materiál.055']: THREE.MeshPhysicalMaterial
    ['Materiál.065']: THREE.MeshPhysicalMaterial
    ['Materiál.057']: THREE.MeshStandardMaterial
    ['Materiál.066']: THREE.MeshPhysicalMaterial
    ['Materiál.067']: THREE.MeshPhysicalMaterial
    ['Materiál.069']: THREE.MeshPhysicalMaterial
    ['Materiál.068']: THREE.MeshPhysicalMaterial
    ['Materiál.070']: THREE.MeshPhysicalMaterial
    ['Materiál.071']: THREE.MeshPhysicalMaterial
    ['Materiál.072']: THREE.MeshPhysicalMaterial
    ['Materiál.073']: THREE.MeshPhysicalMaterial
    ['Materiál.074']: THREE.MeshPhysicalMaterial
    ['Materiál.075']: THREE.MeshPhysicalMaterial
    ['Materiál.076']: THREE.MeshPhysicalMaterial
    ['Materiál.077']: THREE.MeshStandardMaterial
    ['Materiál.078']: THREE.MeshPhysicalMaterial
    ['Materiál.079']: THREE.MeshStandardMaterial
    ['Materiál.080']: THREE.MeshPhysicalMaterial
    ['Materiál.081']: THREE.MeshPhysicalMaterial
    ['Materiál.082']: THREE.MeshPhysicalMaterial
    ['Materiál.083']: THREE.MeshPhysicalMaterial
    ['Materiál.084']: THREE.MeshPhysicalMaterial
    ['Materiál.085']: THREE.MeshPhysicalMaterial
    ['Materiál.086']: THREE.MeshPhysicalMaterial
    ['Materiál.087']: THREE.MeshPhysicalMaterial
    ['Materiál.088']: THREE.MeshPhysicalMaterial
    ['Materiál.093']: THREE.MeshPhysicalMaterial
    ['Materiál.094']: THREE.MeshPhysicalMaterial
    ['Materiál.095']: THREE.MeshPhysicalMaterial
    ['Materiál.097']: THREE.MeshPhysicalMaterial
    ['Materiál.098']: THREE.MeshPhysicalMaterial
  }
}

export function TableWork(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/tableWork.glb') as unknown  as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle002.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle003.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle004.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle005.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle006.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle007.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table.geometry}
        material={materials['Materiál.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle011.geometry}
        material={materials['Materiál.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle012.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle013.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle014.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle015.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle016.geometry}
        material={materials['Materiál.009']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec001.geometry}
        material={materials['Materiál.011']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec002.geometry}
        material={materials['Materiál.011']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle017.geometry}
        material={materials['Materiál.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle018.geometry}
        material={materials['Materiál.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle019.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle020.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle023.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle024.geometry}
        material={materials['Materiál.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle025.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec003.geometry}
        material={materials['Materiál.013']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec004.geometry}
        material={materials['Materiál.006']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={materials['Materiál.022']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec005.geometry}
        material={materials['Materiál.023']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle030.geometry}
        material={materials['Materiál.023']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec007.geometry}
        material={materials['Materiál.038']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec010.geometry}
        material={materials['Materiál.037']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec014.geometry}
        material={materials['Materiál.037']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec016.geometry}
        material={materials['Materiál.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec017.geometry}
        material={materials['Materiál.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka002.geometry}
        material={materials['Materiál.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka003.geometry}
        material={materials['Materiál.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka004.geometry}
        material={materials['Materiál.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka005.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bezierova_křivka001.geometry}
        material={materials['Materiál.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle008.geometry}
        material={materials['Materiál.035']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle009.geometry}
        material={materials['Materiál.035']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle010.geometry}
        material={materials['Materiál.035']}
        position={[-7.377, 4.825, -7.209]}
        rotation={[-0.3, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec008.geometry}
        material={materials['Materiál.035']}
        position={[-7.377, 4.645, -7.663]}
        rotation={[-0.3, 0, -Math.PI / 2]}
        scale={[0.025, 0.044, 0.025]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec009.geometry}
        material={materials['Materiál.013']}
        position={[-7.373, 3.288, -7.388]}
        rotation={[0.1, 0, 0]}
        scale={[0.022, 0.056, 0.022]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec011.geometry}
        material={materials['Materiál.035']}
        position={[-7.373, 3.285, -7.389]}
        rotation={[0.1, 0, 0]}
        scale={[0.023, 0.056, 0.023]}
      />
      <group
        position={[-7.893, 3.408, -5.292]}
        rotation={[0, -0.368, -0.288]}
        scale={[0.005, 0.097, 0.037]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle036_1.geometry}
          material={materials['Materiál.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle036_2.geometry}
          material={materials['Materiál.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle036_3.geometry}
          material={materials['Materiál.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle036_4.geometry}
          material={materials['Materiál.029']}
        />
      </group>
      <group
        position={[-7.587, 3.27, -5.176]}
        rotation={[-Math.PI / 2, 0, 0.434]}
        scale={[0.011, 0.149, 0.011]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec012_1.geometry}
          material={materials['Materiál.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec012_2.geometry}
          material={materials['Materiál.040']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle026.geometry}
        material={materials['Materiál.023']}
        position={[-7.478, 3.292, -3.12]}
        rotation={[0, 0, -0.04]}
        scale={[0.155, 0.003, 0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle028.geometry}
        material={materials['Materiál.023']}
        position={[-7.478, 3.292, -4.259]}
        rotation={[0, 0, -0.04]}
        scale={[0.155, 0.003, 0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle035.geometry}
        material={materials['Materiál.044']}
        position={[-6.9, 3.157, -1.724]}
        scale={[0.156, 0.03, 0.161]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle036.geometry}
        material={materials['Materiál.045']}
        position={[-6.76, 3.155, -1.832]}
        scale={[0.019, 0.019, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle037.geometry}
        material={materials['Materiál.045']}
        position={[-6.76, 3.155, -1.742]}
        scale={[0.019, 0.019, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle055.geometry}
        material={materials['Materiál.054']}
        position={[-7.904, 2.285, -7.637]}
        rotation={[0, -0.373, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec013.geometry}
        material={materials['Materiál.055']}
        position={[-8.164, 2.557, -7.455]}
        rotation={[0, -0.373, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec015.geometry}
        material={materials['Materiál.055']}
        position={[-7.972, 2.556, -7.944]}
        rotation={[0, -0.373, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle061.geometry}
        material={materials['Materiál.065']}
        position={[-9.095, 0.851, -2.002]}
        scale={[0.63, 0.865, 0.642]}
      />
      <group position={[-8.013, 0.885, -2.184]} rotation={[0, 0.827, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle078.geometry}
          material={materials['Materiál.065']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle078_1.geometry}
          material={materials['Materiál.057']}
        />
      </group>
      <group position={[-8.772, 0.997, -1.631]} scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec022_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec022_2.geometry}
          material={materials['Materiál.067']}
        />
      </group>
      <group position={[-8.955, 0.997, -2.261]} scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec023_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec023_2.geometry}
          material={materials['Materiál.067']}
        />
      </group>
      <group
        position={[-8.755, 0.928, -2.503]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec024_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec024_2.geometry}
          material={materials['Materiál.067']}
        />
      </group>
      <group position={[-8.772, 0.206, -1.985]} scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec025_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec025_2.geometry}
          material={materials['Materiál.069']}
        />
      </group>
      <group position={[-8.955, 0.206, -1.652]} scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec026_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec026_2.geometry}
          material={materials['Materiál.069']}
        />
      </group>
      <group
        position={[-8.755, 0.137, -2.25]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec027_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec027_2.geometry}
          material={materials['Materiál.068']}
        />
      </group>
      <group
        position={[-8.755, 0.137, -2.491]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec028_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec028_2.geometry}
          material={materials['Materiál.068']}
        />
      </group>
      <group
        position={[-8.755, 0.341, -2.372]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec029_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec029_2.geometry}
          material={materials['Materiál.068']}
        />
      </group>
      <group position={[-8.772, 0.997, -1.89]} scale={[0.124, 0.194, 0.124]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec030_1.geometry}
          material={materials['Materiál.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec030_2.geometry}
          material={materials['Materiál.067']}
        />
      </group>
      <group position={[-8.482, 3.269, -3.327]} rotation={[0, -0.592, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046.geometry}
          material={materials['Materiál.070']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_1.geometry}
          material={materials['Materiál.071']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_2.geometry}
          material={materials['Materiál.072']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_3.geometry}
          material={materials['Materiál.073']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_4.geometry}
          material={materials['Materiál.074']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_5.geometry}
          material={materials['Materiál.075']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_6.geometry}
          material={materials['Materiál.076']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_7.geometry}
          material={materials['Materiál.077']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_8.geometry}
          material={materials['Materiál.078']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_9.geometry}
          material={materials['Materiál.079']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_10.geometry}
          material={materials['Materiál.080']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_11.geometry}
          material={materials['Materiál.081']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_12.geometry}
          material={materials['Materiál.082']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_13.geometry}
          material={materials['Materiál.083']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_14.geometry}
          material={materials['Materiál.084']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_15.geometry}
          material={materials['Materiál.085']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_16.geometry}
          material={materials['Materiál.086']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_17.geometry}
          material={materials['Materiál.087']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Krychle046_18.geometry}
          material={materials['Materiál.088']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle072.geometry}
        material={materials['Materiál.093']}
        position={[-9.418, 0.624, -3.19]}
        scale={[0.342, 0.634, 0.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle073.geometry}
        material={materials['Materiál.094']}
        position={[-9.418, 1.271, -3.189]}
        scale={[0.431, 0.017, 0.517]}
      />
      <group
        position={[-9.425, 1.284, -3.189]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.407, 0.494, 0.363]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec032.geometry}
          material={materials['Materiál.094']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Válec032_1.geometry}
          material={materials['Materiál.095']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec029.geometry}
        material={materials['Materiál.097']}
        position={[-7.435, 3.403, -6.699]}
        scale={[0.092, 0.147, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec030.geometry}
        material={materials['Materiál.098']}
        position={[-7.435, 3.321, -6.699]}
        scale={[0.089, 0.048, 0.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle010_1.geometry}
        material={materials['Materiál.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle010_2.geometry}
        material={materials['Materiál.008']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kruh_1.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kruh_2.geometry}
        material={materials['Materiál.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kruh001_1.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kruh001_2.geometry}
        material={materials['Materiál.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec_1.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec_2.geometry}
        material={materials['Materiál.012']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle024_1.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle024_2.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle025_1.geometry}
        material={materials['Materiál.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle025_2.geometry}
        material={materials['Materiál.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle030_1.geometry}
        material={materials['Materiál.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle030_2.geometry}
        material={materials['Materiál.014']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle030_3.geometry}
        material={materials['Materiál.018']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle032.geometry}
        material={materials['Materiál.019']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle032_1.geometry}
        material={materials['Materiál.020']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle072_1.geometry}
        material={materials['Materiál.021']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle072_2.geometry}
        material={materials['Materiál.022']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle027_1.geometry}
        material={materials['Materiál.010']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle027_2.geometry}
        material={materials['Materiál.017']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle027_3.geometry}
        material={materials['Materiál.024']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle027_4.geometry}
        material={materials['Materiál.025']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle033.geometry}
        material={materials['Materiál.016']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle033_1.geometry}
        material={materials['Materiál.014']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle033_2.geometry}
        material={materials['Materiál.018']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec006_1.geometry}
        material={materials['Materiál.026']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Válec006_2.geometry}
        material={materials['Materiál.027']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plocha001_1.geometry}
        material={materials['Materiál.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plocha001_2.geometry}
        material={materials['Materiál.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plocha002_1.geometry}
        material={materials['Materiál.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plocha002_2.geometry}
        material={materials['Materiál.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle034.geometry}
        material={materials['Materiál.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Krychle034_1.geometry}
        material={materials['Materiál.042']}
      />
    </group>
  )
}

useGLTF.preload('/models/tableWork.glb')
